#!/bin/bash

passedIn=$*
whereami=$(pwd)
fullpath="${whereami}/${passedIn}"

#https://superuser.com/questions/1068031/replace-backslash-with-forward-slash-in-a-variable-in-bash
#fixing old string filenames
if [[ -f "$fullpath" && "$passedIn" = "[[:space:]]+" ]]; then 
	new_filename=${passedIn// /_}
	#new_filename=${new_filename//\&/'and'}
	mv "$fullpath" "${whereami}/${new_filename}"
	echo "changing name to correct format"
fi


filename=${passedIn// /_} #repeating code
#filename=${filename//&/'and'}

if [[ "$filename" != *.md ]]	
then
	filename=${filename}.md
fi
	
whereami=$(pwd)
fullpath="${whereami}/${filename}"
imagepath="${whereami}/images"


#image folder check
if [[ ! -d "$imagepath" ]];
then
	echo "/images directory being created in path $whereami"
	mkdir $imagepath
fi


#file check
if [[ -z $@ ]]; then #if $@ is null we just open typora
	echo "Opening typora"
	typora . & 

elif [[ -f "$fullpath" ]]; then 
	echo "Opening file $filename"
	typora $filename & 
else
	echo "$fullpath does not exist, creating file $filename"
	touch $filename
	typora $filename &
fi

